#!/usr/bin/env bash
# display "Best School" or "hi" conditionaly

i=1

while (( i <= 10 ))
do
  if (( i == 9 ));
  then
  	echo "Hi"

  fi
  
  if (( i!= 9));
  then
  	echo "Best School"
  fi
  ((i++))
done
